import type { SiteContent } from "@/lib/content-types";

export const defaultContent: SiteContent = {
  siteConfig: {
    name: "Gilang",
    handle: "@GRX199",
    roles: "Data Management & Website Developer",
    location: "Indonesia",
    email: "hello@example.com",
    siteUrl: "https://gilang-portfolio-iota.vercel.app",
    description:
      "Gilang's personal portfolio for profile, projects, tech stack, and contact.",
    headline: "Make it simple",
    bio: "I build portfolio sites, dashboards, and small web tools with Next.js.",
    focus: "frontend, data, automation",
    availability: "available for selected work",
    spotifyUrl:
      "https://open.spotify.com/track/5WOSNVChcadlsCRiqXE45K?si=fdeaf2edceb649c1",
    socials: [
      { label: "GitHub", href: "https://github.com/GRX199" },
      { label: "LinkedIn", href: "https://linkedin.com/" },
      { label: "Instagram", href: "https://instagram.com/" },
    ],
  },
  statusMessages: [
    "Based in Indonesia",
    "Building clean interfaces",
    "Open for selected projects",
  ],
  quickLinks: [
    { label: "Selected projects", href: "/portfolio", icon: "Terminal" },
    { label: "Tech stack", href: "/stack", icon: "Code2" },
    { label: "Collaborate", href: "/collaborate", icon: "Send" },
  ],
  projects: [
    {
      id: "insight-dashboard",
      title: "Insight Dashboard",
      year: "2026",
      status: "Live",
      description:
        "A data dashboard for monitoring operational metrics, performance trends, and concise reports.",
      tags: ["Next.js", "Charts", "PostgreSQL"],
      image: "/projects/dashboard.svg",
      href: "/collaborate",
      icon: "LayoutDashboard",
      featured: true,
    },
    {
      id: "coffee-time",
      title: "CoffeeTime",
      year: "2026",
      status: "In Progress",
      description:
        "A modern coffee shop landing page with immersive visuals and a responsive layout.",
      tags: ["Next.js", "Tailwind CSS", "Framer Motion"],
      image: "/projects/store.svg",
      href: "/collaborate",
      icon: "Coffee",
      featured: true,
    },
    {
      id: "workflow-automation",
      title: "Workflow Automation",
      year: "2025",
      status: "Internal Tool",
      description:
        "An automation system for notifications, data logging, and scheduled reports.",
      tags: ["Node.js", "API", "Sheets"],
      image: "/projects/automation.svg",
      href: "/collaborate",
      icon: "Workflow",
      featured: true,
    },
    {
      id: "schoolify",
      title: "Schoolify",
      year: "2025",
      status: "Case Study",
      description:
        "A school management platform with calendars, charts, authentication, and a Prisma database.",
      tags: ["Next.js", "Prisma", "PostgreSQL", "Charts"],
      image: "/projects/dashboard.svg",
      href: "/collaborate",
      icon: "GraduationCap",
      featured: false,
    },
    {
      id: "launch-page",
      title: "Launch Page",
      year: "2024",
      status: "Archived",
      description:
        "A product launch page with editorial visuals and lightweight animation.",
      tags: ["Next.js", "Motion", "SEO"],
      image: "/projects/launch.svg",
      href: "/collaborate",
      icon: "Rocket",
      featured: false,
    },
  ],
  stackItems: [
    { id: "nextjs", name: "Next.js", category: "core", icon: "MonitorSmartphone" },
    { id: "react", name: "React", category: "core", icon: "Code2" },
    { id: "typescript", name: "TypeScript", category: "language", icon: "Braces" },
    { id: "tailwind", name: "Tailwind CSS", category: "framework", icon: "Palette" },
    { id: "nodejs", name: "Node.js", category: "framework", icon: "Server" },
    { id: "postgresql", name: "PostgreSQL", category: "tool", icon: "Database" },
    { id: "rest-api", name: "REST API", category: "framework", icon: "Globe2" },
    { id: "automation", name: "Automation", category: "core", icon: "Workflow" },
    { id: "github", name: "GitHub", category: "tool", icon: "GitPullRequest" },
    { id: "figma", name: "Figma", category: "tool", icon: "PenTool" },
    { id: "vercel", name: "Vercel", category: "tool", icon: "Gauge" },
    { id: "email", name: "Email", category: "tool", icon: "Mail" },
  ],
  contactIntents: [
    "Portfolio website",
    "Landing page",
    "Dashboard",
    "Automation tool",
  ],
};
